version: '3.8'

services:
  projectms-api:
    image: ghcr.io/gradovenko/projectmanagementsystem.api:master
    environment:
      - ConnectionStrings:ProjectMS=Server=projectms-db;Port=5432;Database=ProjectMS;User ID=ProjectMS;Password=TRrkyqX43MJYZt3J;
    depends_on:
      - projectms-db
    restart: always

  projectms-nginx:
    image: nginx:1.23.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  projectms-db:
    image: postgres:15.2-alpine
    command: 
      - postgres
      - --shared_buffers=256MB
      - --max_connections=1000
      - --wal_level=logical
    ports:
      - "5432:5432"
    volumes:
      - /var/log/projectms/postgresql/:/var/log/postgresql
      - /var/lib/projectms/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ProjectMS
      - POSTGRES_USER=ProjectMS
      - POSTGRES_PASSWORD=TRrkyqX43MJYZt3J
      - PGDATA=/var/lib/postgresql/data/projectms
    restart: always