version: '3.4'

services:
  projectms-webapi:
    image: grad1242/projectmanagementsystem.webapi:latest
    volumes:
      - /docker-data/projectms/logs/projectms-webapi/:/app/logs
    environment:
      - ConnectionStrings:ProjectMS=Server=projectms-db;Port=5432;Database=${POSTGRES_DB};User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
    depends_on:
      - projectms-db
    restart: always

  projectms-nginx:
    image: nginx:1.17.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /docker-data/projectms/logs/proxy/:/var/log/nginx
    restart: always

  projectms-db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgresql.conf:/var/lib/postgresql/data/projectms/postgresql.conf
      - projectms-pgdata:/var/lib/postgresql/data
      - projectms-pglogs:/var/log/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/projectms2
    restart: always

volumes:
  projectms-pgdata:
    driver: local
  projectms-pglogs:
    driver: local