version: '3.4'

services:
  projectms-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgresql.conf:/var/lib/postgresql/data/projectms/postgresql.conf
      - projectms-pgdata:/var/lib/postgresql/data
      - projectms-pglogs:/var/log/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/projectms-data

volumes:
  projectms-pgdata:
    driver: local
  projectms-pglogs:
    driver: local